#############################################################################
# Makefile for building: Projector_remote_control
# Generated by qmake (3.1) (Qt 6.4.2)
# Project:  Projector_remote_control.pro
# Template: app
# Command: /home/xavier/Qt/6.4.2/gcc_64/bin/qmake -o Makefile Projector_remote_control.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++1z -Wall -Wextra -fPIC -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I../../Qt/6.4.2/gcc_64/include -I../../Qt/6.4.2/gcc_64/include/QtWidgets -I../../Qt/6.4.2/gcc_64/include/QtGui -I../../Qt/6.4.2/gcc_64/include/QtNetwork -I../../Qt/6.4.2/gcc_64/include/QtCore -I. -I. -I../../Qt/6.4.2/gcc_64/mkspecs/linux-g++
QMAKE         = /home/xavier/Qt/6.4.2/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/xavier/Qt/6.4.2/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/xavier/Qt/6.4.2/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Projector_remote_control1.0.0
DISTDIR = /home/xavier/Music/Projector_remote_control/.tmp/Projector_remote_control1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/xavier/Qt/6.4.2/gcc_64/lib -Wl,-rpath-link,/home/xavier/Qt/6.4.2/gcc_64/lib
LIBS          = $(SUBLIBS) /home/xavier/Qt/6.4.2/gcc_64/lib/libQt6Widgets.so /home/xavier/Qt/6.4.2/gcc_64/lib/libQt6Gui.so /home/xavier/Qt/6.4.2/gcc_64/lib/libQt6Network.so /home/xavier/Qt/6.4.2/gcc_64/lib/libQt6Core.so -lpthread -lGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = connectthread.cpp \
		main.cpp \
		mainwindow.cpp qrc_Image.cpp \
		qrc_rs.cpp \
		qrc_qmake_qmake_immediate.cpp \
		moc_connectthread.cpp \
		moc_mainwindow.cpp
OBJECTS       = connectthread.o \
		main.o \
		mainwindow.o \
		qrc_Image.o \
		qrc_rs.o \
		qrc_qmake_qmake_immediate.o \
		moc_connectthread.o \
		moc_mainwindow.o
DIST          = ../../Qt/6.4.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/unix.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/linux.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/qconfig.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.4.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qt.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/resources.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/moc.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/uic.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/lex.prf \
		Projector_remote_control.pro connectthread.h \
		mainwindow.h \
		styles.h connectthread.cpp \
		main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = Projector_remote_control
DESTDIR       = 
TARGET        = Projector_remote_control


first: all
####### Build rules

Projector_remote_control: ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Projector_remote_control.pro ../../Qt/6.4.2/gcc_64/mkspecs/linux-g++/qmake.conf ../../Qt/6.4.2/gcc_64/mkspecs/features/spec_pre.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/unix.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/linux.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/sanitize.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/gcc-base.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/g++-base.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/common/g++-unix.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/qconfig.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qt_functions.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qt_config.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/6.4.2/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/toolchain.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/default_pre.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/resolve_config.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/default_post.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qml_debug.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/warn_on.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qt.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/resources_functions.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/resources.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/moc.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/unix/opengl.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/uic.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/unix/thread.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/qmake_use.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/file_copies.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/testcase_targets.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/exceptions.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/yacc.prf \
		../../Qt/6.4.2/gcc_64/mkspecs/features/lex.prf \
		Projector_remote_control.pro \
		Image.qrc \
		rs.qrc \
		qmake_qmake_immediate.qrc \
		../../Qt/6.4.2/gcc_64/lib/libQt6Widgets.prl \
		../../Qt/6.4.2/gcc_64/lib/libQt6Gui.prl \
		../../Qt/6.4.2/gcc_64/lib/libQt6Network.prl \
		../../Qt/6.4.2/gcc_64/lib/libQt6Core.prl
	$(QMAKE) -o Makefile Projector_remote_control.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
../../Qt/6.4.2/gcc_64/mkspecs/features/spec_pre.prf:
../../Qt/6.4.2/gcc_64/mkspecs/common/unix.conf:
../../Qt/6.4.2/gcc_64/mkspecs/common/linux.conf:
../../Qt/6.4.2/gcc_64/mkspecs/common/sanitize.conf:
../../Qt/6.4.2/gcc_64/mkspecs/common/gcc-base.conf:
../../Qt/6.4.2/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../Qt/6.4.2/gcc_64/mkspecs/common/g++-base.conf:
../../Qt/6.4.2/gcc_64/mkspecs/common/g++-unix.conf:
../../Qt/6.4.2/gcc_64/mkspecs/qconfig.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_ext_libjpeg.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_ext_libpng.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_harfbuzz_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_jpeg_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsanimation.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsanimation_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssettings.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssettings_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labssharedimage_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_linguist.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_linguist_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_openglwidgets_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_png_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcore.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlcore_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmldom_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlintegration_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicklayouts_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_svgwidgets_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_tools_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandclient.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandclient_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_waylandglobal_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../Qt/6.4.2/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/6.4.2/gcc_64/mkspecs/features/qt_functions.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/qt_config.prf:
../../Qt/6.4.2/gcc_64/mkspecs/linux-g++/qmake.conf:
../../Qt/6.4.2/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/6.4.2/gcc_64/mkspecs/features/exclusive_builds.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/toolchain.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/default_pre.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/resolve_config.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/default_post.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/qml_debug.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/warn_on.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/qt.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/resources_functions.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/resources.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/moc.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/unix/opengl.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/uic.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/unix/thread.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/qmake_use.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/file_copies.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/testcase_targets.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/exceptions.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/yacc.prf:
../../Qt/6.4.2/gcc_64/mkspecs/features/lex.prf:
Projector_remote_control.pro:
Image.qrc:
rs.qrc:
qmake_qmake_immediate.qrc:
../../Qt/6.4.2/gcc_64/lib/libQt6Widgets.prl:
../../Qt/6.4.2/gcc_64/lib/libQt6Gui.prl:
../../Qt/6.4.2/gcc_64/lib/libQt6Network.prl:
../../Qt/6.4.2/gcc_64/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Projector_remote_control.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile Projector_remote_control

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Image.qrc rs.qrc qmake_qmake_immediate.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../Qt/6.4.2/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents connectthread.h mainwindow.h styles.h $(DISTDIR)/
	$(COPY_FILE) --parents connectthread.cpp main.cpp mainwindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Image.cpp qrc_rs.cpp qrc_qmake_qmake_immediate.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Image.cpp qrc_rs.cpp qrc_qmake_qmake_immediate.cpp
qrc_Image.cpp: Image.qrc \
		../../Qt/6.4.2/gcc_64/libexec/rcc \
		power-btn.png \
		On.png \
		HDBaseT.png \
		DisplayPort.png \
		Off \
		SDI.svg \
		HDMI.png \
		LAN_Port.png
	/home/xavier/Qt/6.4.2/gcc_64/libexec/rcc -name Image --no-zstd Image.qrc -o qrc_Image.cpp

qrc_rs.cpp: rs.qrc \
		../../Qt/6.4.2/gcc_64/libexec/rcc \
		utils.txt
	/home/xavier/Qt/6.4.2/gcc_64/libexec/rcc -name rs --no-zstd rs.qrc -o qrc_rs.cpp

qrc_qmake_qmake_immediate.cpp: qmake_qmake_immediate.qrc \
		../../Qt/6.4.2/gcc_64/libexec/rcc \
		utils.txt
	/home/xavier/Qt/6.4.2/gcc_64/libexec/rcc -name qmake_qmake_immediate --no-zstd qmake_qmake_immediate.qrc -o qrc_qmake_qmake_immediate.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Qt/6.4.2/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++1z -Wall -Wextra -fPIC -dM -E -o moc_predefs.h ../../Qt/6.4.2/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_connectthread.cpp moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_connectthread.cpp moc_mainwindow.cpp
moc_connectthread.cpp: connectthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QThread \
		../../Qt/6.4.2/gcc_64/include/QtCore/qthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlogging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qflags.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qforeach.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstring.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qchar.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpair.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qanystringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterator.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopeguard.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterable.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmath.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdebug.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qset.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhash.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvariant.h \
		moc_predefs.h \
		../../Qt/6.4.2/gcc_64/libexec/moc
	/home/xavier/Qt/6.4.2/gcc_64/libexec/moc $(DEFINES) --include /home/xavier/Music/Projector_remote_control/moc_predefs.h -I/home/xavier/Qt/6.4.2/gcc_64/mkspecs/linux-g++ -I/home/xavier/Music/Projector_remote_control -I/home/xavier/Qt/6.4.2/gcc_64/include -I/home/xavier/Qt/6.4.2/gcc_64/include/QtWidgets -I/home/xavier/Qt/6.4.2/gcc_64/include/QtGui -I/home/xavier/Qt/6.4.2/gcc_64/include/QtNetwork -I/home/xavier/Qt/6.4.2/gcc_64/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include connectthread.h -o moc_connectthread.cpp

moc_mainwindow.cpp: mainwindow.h \
		connectthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QThread \
		../../Qt/6.4.2/gcc_64/include/QtCore/qthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlogging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qflags.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qforeach.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstring.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qchar.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpair.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qanystringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterator.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopeguard.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterable.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmath.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdebug.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qset.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhash.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvariant.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtgui-config.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtguiexports.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qicon.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsize.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmargins.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrect.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpoint.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qcolor.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qrgb.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qrgba64.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qimage.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtransform.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qregion.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qline.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qaction.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpalette.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qbrush.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfont.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qcursor.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qbitmap.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qevent.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qurl.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qeventpoint.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qvectornd.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpointingdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qinputdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qscreen.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QList \
		../../Qt/6.4.2/gcc_64/include/QtCore/QObject \
		../../Qt/6.4.2/gcc_64/include/QtCore/QRect \
		../../Qt/6.4.2/gcc_64/include/QtCore/QSize \
		../../Qt/6.4.2/gcc_64/include/QtCore/QSizeF \
		../../Qt/6.4.2/gcc_64/include/QtGui/QTransform \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnativeinterface.h \
		ui_mainwindow.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QGraphicsOpacityEffect \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qgraphicseffect.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QPropertyAnimation \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvariantanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qabstractanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qeasingcurve.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QEasingCurve \
		styles.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QFile \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfile.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QSlider \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qslider.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qabstractslider.h \
		moc_predefs.h \
		../../Qt/6.4.2/gcc_64/libexec/moc
	/home/xavier/Qt/6.4.2/gcc_64/libexec/moc $(DEFINES) --include /home/xavier/Music/Projector_remote_control/moc_predefs.h -I/home/xavier/Qt/6.4.2/gcc_64/mkspecs/linux-g++ -I/home/xavier/Music/Projector_remote_control -I/home/xavier/Qt/6.4.2/gcc_64/include -I/home/xavier/Qt/6.4.2/gcc_64/include/QtWidgets -I/home/xavier/Qt/6.4.2/gcc_64/include/QtGui -I/home/xavier/Qt/6.4.2/gcc_64/include/QtNetwork -I/home/xavier/Qt/6.4.2/gcc_64/include/QtCore -I/usr/include/c++/12 -I/usr/include/x86_64-linux-gnu/c++/12 -I/usr/include/c++/12/backward -I/usr/lib/gcc/x86_64-linux-gnu/12/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		../../Qt/6.4.2/gcc_64/libexec/uic
	/home/xavier/Qt/6.4.2/gcc_64/libexec/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

connectthread.o: connectthread.cpp connectthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QThread \
		../../Qt/6.4.2/gcc_64/include/QtCore/qthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlogging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qflags.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qforeach.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstring.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qchar.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpair.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qanystringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterator.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopeguard.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterable.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmath.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdebug.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qset.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhash.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvariant.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QMutex \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmutex.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtsan_impl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o connectthread.o connectthread.cpp

main.o: main.cpp mainwindow.h \
		connectthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QThread \
		../../Qt/6.4.2/gcc_64/include/QtCore/qthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlogging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qflags.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qforeach.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstring.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qchar.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpair.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qanystringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterator.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopeguard.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterable.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmath.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdebug.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qset.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhash.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvariant.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtgui-config.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtguiexports.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qicon.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsize.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmargins.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrect.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpoint.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qcolor.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qrgb.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qrgba64.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qimage.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtransform.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qregion.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qline.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qaction.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpalette.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qbrush.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfont.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qcursor.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qbitmap.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qevent.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qurl.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qeventpoint.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qvectornd.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpointingdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qinputdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qscreen.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QList \
		../../Qt/6.4.2/gcc_64/include/QtCore/QObject \
		../../Qt/6.4.2/gcc_64/include/QtCore/QRect \
		../../Qt/6.4.2/gcc_64/include/QtCore/QSize \
		../../Qt/6.4.2/gcc_64/include/QtCore/QSizeF \
		../../Qt/6.4.2/gcc_64/include/QtGui/QTransform \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnativeinterface.h \
		ui_mainwindow.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QGraphicsOpacityEffect \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qgraphicseffect.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QPropertyAnimation \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvariantanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qabstractanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qeasingcurve.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QEasingCurve \
		styles.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QFile \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfile.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QSlider \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qslider.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qabstractslider.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QApplication \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qapplication.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcoreapplication.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qeventloop.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcoreapplication_platform.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qjnitypes.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfuture.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfutureinterface.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmutex.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtsan_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qresultstore.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfuture_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qthreadpool.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrunnable.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qexception.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpromise.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qguiapplication.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qinputmethod.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlocale.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qguiapplication_platform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		connectthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QThread \
		../../Qt/6.4.2/gcc_64/include/QtCore/qthread.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnamespace.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qconfig.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcore-config.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtconfigmacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtcoreexports.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsystemdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qprocessordetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompilerdetection.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtypeinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsysinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlogging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qflags.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbasicatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qgenericatomic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qglobalstatic.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnumeric.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qversiontagging.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qforeach.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtmetamacros.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstring.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qchar.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrefcount.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpair.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydatapointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qarraydataops.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainertools_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearrayview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringfwd.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringliteral.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qanystringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qutf8stringview.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringtokenizer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringbuilder.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhashfunctions.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterator.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbytearraylist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringlist.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qalgorithms.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringmatcher.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcoreevent.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetatype.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcompare.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qscopeguard.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdatastream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevicebase.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiterable.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmetacontainer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontainerinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtaggedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmath.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qobject_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qbindingstorage.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdeadlinetimer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qelapsedtimer.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/QTcpSocket \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtcpsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetwork-config.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qtnetworkexports.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qabstractsocket.h \
		../../Qt/6.4.2/gcc_64/include/QtNetwork/qhostaddress.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qiodevice.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qdebug.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtextstream.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qstringconverter_base.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qcontiguouscache.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmap.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qshareddata_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qset.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qhash.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvarlengtharray.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvariant.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qpushbutton.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtguiglobal.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtgui-config.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtguiexports.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtwidgetsexports.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qicon.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qsize.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmargins.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpixmap.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpaintdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qwindowdefs.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrect.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpoint.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qcolor.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qrgb.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qrgba64.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qimage.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpixelformat.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qtransform.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpolygon.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qregion.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qline.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qkeysequence.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qwidget.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qaction.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpalette.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qbrush.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfont.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfontmetrics.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qfontinfo.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qcursor.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qbitmap.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qevent.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpointer.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qurl.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qeventpoint.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qvector2d.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qvectornd.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qpointingdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qinputdevice.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/qscreen.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QList \
		../../Qt/6.4.2/gcc_64/include/QtCore/QObject \
		../../Qt/6.4.2/gcc_64/include/QtCore/QRect \
		../../Qt/6.4.2/gcc_64/include/QtCore/QSize \
		../../Qt/6.4.2/gcc_64/include/QtCore/QSizeF \
		../../Qt/6.4.2/gcc_64/include/QtGui/QTransform \
		../../Qt/6.4.2/gcc_64/include/QtCore/qnativeinterface.h \
		ui_mainwindow.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QMainWindow \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qmainwindow.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qtabwidget.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QGraphicsOpacityEffect \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qgraphicseffect.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QPropertyAnimation \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpropertyanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qvariantanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qabstractanimation.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qeasingcurve.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QEasingCurve \
		styles.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QFile \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfile.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfiledevice.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QSlider \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qslider.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qabstractslider.h \
		../../Qt/6.4.2/gcc_64/include/QtGui/QValidator \
		../../Qt/6.4.2/gcc_64/include/QtGui/qvalidator.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qregularexpression.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qlocale.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/QRegularExpression \
		../../Qt/6.4.2/gcc_64/include/QtGui/QRegularExpressionValidator \
		../../Qt/6.4.2/gcc_64/include/QtGui/QShortcut \
		../../Qt/6.4.2/gcc_64/include/QtGui/qshortcut.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/QHBoxLayout \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qboxlayout.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qlayout.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../Qt/6.4.2/gcc_64/include/QtWidgets/qgridlayout.h \
		../../Qt/6.4.2/gcc_64/include/QtConcurrent/QtConcurrentRun \
		../../Qt/6.4.2/gcc_64/include/QtConcurrent/qtconcurrentrun.h \
		../../Qt/6.4.2/gcc_64/include/QtConcurrent/qtconcurrentcompilertest.h \
		../../Qt/6.4.2/gcc_64/include/QtConcurrent/qtconcurrent_global.h \
		../../Qt/6.4.2/gcc_64/include/QtConcurrent/qtconcurrentexports.h \
		../../Qt/6.4.2/gcc_64/include/QtConcurrent/qtconcurrentrunbase.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfuture.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfutureinterface.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qmutex.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qtsan_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qresultstore.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qfuture_impl.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qthreadpool.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qrunnable.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qexception.h \
		../../Qt/6.4.2/gcc_64/include/QtCore/qpromise.h \
		../../Qt/6.4.2/gcc_64/include/QtConcurrent/qtconcurrentstoredfunctioncall.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_Image.o: qrc_Image.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Image.o qrc_Image.cpp

qrc_rs.o: qrc_rs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_rs.o qrc_rs.cpp

qrc_qmake_qmake_immediate.o: qrc_qmake_qmake_immediate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qmake_qmake_immediate.o qrc_qmake_qmake_immediate.cpp

moc_connectthread.o: moc_connectthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_connectthread.o moc_connectthread.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Projector_remote_control/bin || mkdir -p $(INSTALL_ROOT)/opt/Projector_remote_control/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/Projector_remote_control/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/Projector_remote_control/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Projector_remote_control/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

